/**
 * Share Engine — push .bug artifacts to GitHub Gist
 * 
 * Creates a secret gist with the artifact contents for easy sharing.
 * Recipients can download and replay with: bugproof pull <gist-url>
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as https from 'https';
import { HttpsProxyAgent } from 'https-proxy-agent';
import { extractZip } from '../utils/archive.js';

export interface ShareResult {
  url: string;
  gistId: string;
  rawUrl: string;
}

interface GistFile {
  content: string;
}

export function sanitizeShareError(input: string): string {
  return input
    .replace(/Bearer\s+[A-Za-z0-9_\-.]+/gi, 'Bearer [REDACTED]')
    .replace(/(gh[pousr]_[A-Za-z0-9_]+)/g, '[REDACTED_TOKEN]')
    .replace(/("authorization"\s*:\s*")([^"]+)(")/gi, '$1[REDACTED]$3')
    .replace(/(token\s*[=:]\s*)([^\s,]+)/gi, '$1[REDACTED]');
}

/**
 * Uploads artifact contents to a GitHub Gist.
 * Requires GITHUB_TOKEN or BUGPROOF_GITHUB_TOKEN env var.
 */
export async function shareToGist(
  artifactPath: string,
  options: { public?: boolean; description?: string } = {},
): Promise<ShareResult> {
  const token = process.env.BUGPROOF_GITHUB_TOKEN || process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error(
      'GitHub token required for sharing. Set GITHUB_TOKEN or BUGPROOF_GITHUB_TOKEN environment variable.\n' +
      'Create a token at: https://github.com/settings/tokens (needs "gist" scope)',
    );
  }

  // Extract artifact if it's a zip
  let extractDir: string | undefined;
  let targetDir: string;

  const stat = fs.statSync(artifactPath);
  if (stat.isFile()) {
    extractDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bugproof-share-'));
    await extractZip(artifactPath, extractDir);
    targetDir = extractDir;
  } else {
    targetDir = artifactPath;
  }

  try {
    // Read key files from the artifact
    const files: Record<string, GistFile> = {};
    const keyFiles = ['manifest.json', 'failure.json', 'run.json', 'env.schema.json'];

    for (const filename of keyFiles) {
      const filePath = path.join(targetDir, filename);
      if (fs.existsSync(filePath)) {
        files[filename] = { content: fs.readFileSync(filePath, 'utf-8') };
      }
    }

    // Add a README for context
    const manifest = JSON.parse(fs.readFileSync(path.join(targetDir, 'manifest.json'), 'utf-8'));
    files['README.md'] = {
      content: generateGistReadme(manifest),
    };

    // Add stderr/stdout logs if they exist
    const stderrPath = path.join(targetDir, 'stderr.log');
    const stdoutPath = path.join(targetDir, 'stdout.log');
    if (fs.existsSync(stderrPath)) {
      const content = fs.readFileSync(stderrPath, 'utf-8');
      if (content.length <= 100000) { // Gist file size limit
        files['stderr.log'] = { content };
      }
    }
    if (fs.existsSync(stdoutPath)) {
      const content = fs.readFileSync(stdoutPath, 'utf-8');
      if (content.length <= 100000) {
        files['stdout.log'] = { content };
      }
    }

    // Create the gist
    const gistData = JSON.stringify({
      description: options.description || `BugProof: ${manifest.name} — ${manifest.description}`,
      public: options.public || false,
      files,
    });

    const result = await httpPost('https://api.github.com/gists', gistData, token);
    const parsed = JSON.parse(result);

    return {
      url: parsed.html_url,
      gistId: parsed.id,
      rawUrl: parsed.html_url + '/raw',
    };
  } finally {
    if (extractDir) {
      fs.rmSync(extractDir, { recursive: true, force: true });
    }
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateGistReadme(manifest: any): string {
  return `# BugProof Artifact: ${manifest.name}

> ${manifest.description}

## Quick Replay

\`\`\`bash
# Download and replay this bug:
bugproof pull ${manifest.name}
\`\`\`

## Details

| Field | Value |
|-------|-------|
| Command | \`${manifest.command.join(' ')}\` |
| Exit Code | ${manifest.exit_code} |
| Platform | ${manifest.captured_on.os}/${manifest.captured_on.arch} |
| Node | ${manifest.captured_on.node_version} |
| Captured | ${manifest.captured_at} |
| Git | ${manifest.captured_on.git_branch || 'n/a'} @ ${(manifest.captured_on.git_commit || 'n/a').slice(0, 8)} |

## Files

${manifest.files_count} files captured (${(manifest.files_size_bytes / 1024).toFixed(1)} KB)

---
*Generated by [BugProof](https://github.com/sidinsearch/BugProof) v${manifest.bugproof_version}*
`;
}

function httpPost(url: string, data: string, token: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const urlObj = new URL(url);
    const proxy = process.env.HTTPS_PROXY || process.env.https_proxy || process.env.HTTP_PROXY || process.env.http_proxy;
    const agent = proxy ? new HttpsProxyAgent(proxy) : undefined;

    const options: https.RequestOptions = {
      hostname: urlObj.hostname,
      port: 443,
      path: urlObj.pathname,
      method: 'POST',
      agent,
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
        'User-Agent': 'BugProof-CLI',
        'Accept': 'application/vnd.github+json',
        'Content-Length': Buffer.byteLength(data),
      },
    };

    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', (chunk) => { body += chunk; });
      res.on('end', () => {
        if (res.statusCode && res.statusCode >= 200 && res.statusCode < 300) {
          resolve(body);
        } else {
          reject(new Error(sanitizeShareError(`GitHub API error ${res.statusCode}: ${body}`)));
        }
      });
    });

    req.on('error', (err) => {
      reject(new Error(sanitizeShareError(String(err))));
    });
    req.write(data);
    req.end();
  });
}
